### ISSUE TITLE
Bluemage RSR profile

### ISSUE THREAD

**Issue by Cypher-Element** [spaceelysian/pvp-rotations#1]
Is there a list of required spells that I need to have/enable for this to work?

**Comment by spaceelysian** [comment]
I haven't really fleshed out the blue mage because it'll be a bit of a job with a hundred different spells.  I'll work on it some this weekend, but right now it just casts SonicBoom and some oGCDs:  Quasar, ShockStrike, GlassDance, BeingMortal, SeaShanty, Nightbloom.

**Comment by Cypher-Element** [comment]
Thank you, I appreciate your quick response. I found some resources that may help as far as rotations go, let me  know if you want me to link that.
